services:
    riverway.grid:
        class: Riverway\Grid\Widget\GridWidget
        arguments: ['@knp_paginator', '@translator', '@templating.engine.twig']
        calls:
            - [setRequest, ['@request_stack']]
