services:
    Riverway\Grid\Widget\GridWidget:
        autowire: true
        autoconfigure: true
        calls:
            - [setRequest, ['@request_stack']]
        public: true
    Riverway\Grid\Twig\RiverwayGridExtension:
        autowire: true
        autoconfigure: true
        tags:
            - { name: 'twig.extension' }
